/**
 * The real architecture, end to end, in real browsers.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * Vahid, 2026-08-28: *"Test the actual architecture in real browsers, not only
 * hook adapters."*
 *
 *   Browser → Conversation Service → PostgreSQL → server-assigned ordinal
 *           → SSE → ConversationLog → React UI
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Every assertion below runs against a real Chromium page, a real Express
 * server, a real PostgreSQL log and a real `EventSource`. There is no stubbed
 * transport in this file: an adapter test can prove the hook obeys a rule, and
 * cannot prove the browser reaches the service at all — which is the thing this
 * phase adds.
 *
 * ── Why this file lives here ──────────────────────────────────────────────
 *
 * The React client is still housed in `apps/chat-integration` while the legacy
 * harness is retired (see `docs/harness-coverage-mapping.md`), and the bundler
 * that builds it is here too. So the test that boots the real Conversation
 * Service lives beside the client it serves, with the service as a
 * devDependency. It moves with the client.
 */

import type { Server } from "node:http";
import { join } from "node:path";
import { cp, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { chromium, type Browser, type Page } from "playwright";
import pg from "pg";

import { migrate } from "@askimate/aas-migrate";
import { announceSkip, databaseReachable, TEST_DATABASE_URL } from "@askimate/aas-migrate/testing";
import {
  ConversationEventStore,
  MIGRATIONS_DIR,
  createConversationApp,
} from "@askimate/aas-conversation-service";

import { buildChatClient } from "./build-client.js";

const PORT = 4839;
const BASE = `http://127.0.0.1:${String(PORT)}`;
const SESSION_SECRET = "conversation-plane-session-secret-for-tests";
/** The mTLS stand-in the internal append route accepts. */
const SERVICE_CERT = "secure-service";
const NOW = new Date("2026-08-28T10:00:00Z");

const HAVE_DATABASE = await databaseReachable();
if (!HAVE_DATABASE) announceSkip("apps/chat-integration/src/conversation-service.test.ts");
const describeIfDatabase = HAVE_DATABASE ? describe : describe.skip;

let pool: pg.Pool;
let store: ConversationEventStore;
let server: Server;
let browser: Browser;
let clientDir: string;
let studentId: string;
let otherStudentId: string;

/**
 * A fresh conversation owned by `owner`.
 *
 * The id is supplied, not generated by the database: `conversations.id` is a
 * ULID with a CHECK constraint carrying the exact pattern the contract
 * publishes, so the column will not hold a value the contract forbids. A test
 * that let PostgreSQL invent one would be testing a different id space.
 */
let counter = 0;

/**
 * What the SERVER received on the `Last-Event-ID` header of every `/stream`
 * request, oldest first. `null` means the request carried no such header.
 *
 * The server, not the browser-side listener, because the server is the only
 * observer that cannot be wrong about this. Playwright's `request.headers()`
 * is a snapshot of the request as the page issued it and documents itself as
 * incomplete — `allHeaders()` exists precisely because some headers are added
 * below it. `Last-Event-ID` is one the browser adds on its own. Asserting on
 * the client-side snapshot is asserting about the instrument; asserting on
 * what arrived at the service is asserting about the guarantee, which is what
 * ADR-0035 actually promises: a reconnect resumes from the header, and the
 * service honours it.
 */
interface StreamObservation {
  /** `Last-Event-ID` as the SERVICE received it, or `null` if absent. */
  readonly resumeFrom: string | null;
  /** The ordinals the service wrote back on THIS connection, in order. */
  readonly delivered: number[];
}

const streamObservations: StreamObservation[] = [];

/** Just the resume cursors, oldest first — the common case. */
const resumeCursors = (): (string | null)[] =>
  streamObservations.map((observation) => observation.resumeFrom);
async function newConversation(owner: string = studentId): Promise<string> {
  counter += 1;
  const id = `01JBXQ8Z9WKTQ6M4H2NPB${String(counter).padStart(5, "0")}`;
  await pool.query("INSERT INTO conversations (id, student_id) VALUES ($1, $2)", [id, owner]);
  return id;
}

/**
 * A logged-in page on a conversation.
 *
 * The session is a real `__Host-` cookie, set by the browser from a real
 * `Set-Cookie`. Not injected with `addCookies`: `__Host-` has browser-enforced
 * rules — Secure, Path=/, no Domain — and a test that set the cookie by hand
 * would prove the page works with a cookie the browser would have refused.
 */
async function chatPage(
  conversationId: string,
  subject: string = studentId,
): Promise<Page> {
  const context = await browser.newContext();
  const page = await context.newPage();

  const response = await page.request.post(`${BASE}/dev/session`, {
    data: { subject },
    headers: { "Content-Type": "application/json" },
  });
  expect(response.status(), "the session route must mint a cookie").toBe(204);

  await page.addInitScript((id) => {
    (window as unknown as Record<string, unknown>)["__askimateDurableConversationId"] = id;
  }, conversationId);
  await page.goto(`${BASE}/index.html`);
  await page.locator('[data-testid="composer"]').waitFor({ state: "visible" });
  // The durable transcript has arrived. Asserting before this would be
  // asserting about a page that had not finished loading — and an empty
  // transcript would look like agreement.
  await page.waitForFunction(
    () => (window as unknown as { __askimateLoaded?: () => boolean }).__askimateLoaded?.() === true,
    undefined,
    { timeout: 15_000 },
  );
  return page;
}

/** The DURABLE events a page holds — the ones with server ordinals. */
async function durableOf(page: Page): Promise<{ ordinal: number; content: unknown }[]> {
  return (await page.evaluate(() =>
    (window as unknown as { __askimateDurable: () => unknown }).__askimateDurable(),
  )) as { ordinal: number; content: unknown }[];
}

/** Everything a page holds, durable and provisional. */
async function allOf(page: Page): Promise<unknown[]> {
  return (await page.evaluate(() =>
    (window as unknown as { __askimateTurns: () => unknown }).__askimateTurns(),
  )) as unknown[];
}

async function sendFromComposer(page: Page, text: string): Promise<void> {
  await page.locator("#chat-input").fill(text);
  await page.locator("#chat-send").click();
}

beforeAll(async () => {
  if (!HAVE_DATABASE) return;
  const admin = new pg.Pool({ connectionString: TEST_DATABASE_URL });
  try {
    await admin.query("DROP DATABASE IF EXISTS aas_conversation_browser WITH (FORCE)");
    await admin.query("CREATE DATABASE aas_conversation_browser");
  } finally {
    await admin.end();
  }
  const url = new URL(TEST_DATABASE_URL);
  url.pathname = "/aas_conversation_browser";
  pool = new pg.Pool({ connectionString: url.toString(), max: 16 });
  await migrate(pool, MIGRATIONS_DIR);
  store = new ConversationEventStore(pool);

  const students = await pool.query<{ id: string }>(
    `INSERT INTO students (subject, email_verified) VALUES ('oidc-browser-a', true),
                                                          ('oidc-browser-b', true) RETURNING id`,
  );
  studentId = students.rows[0]!.id;
  otherStudentId = students.rows[1]!.id;

  clientDir = await mkdtemp(join(tmpdir(), "aas-conv-client-"));
  await cp(join(import.meta.dirname, "..", "public", "index.html"), join(clientDir, "index.html"));
  await buildChatClient(join(clientDir, "chat-client.js"));

  const app = createConversationApp({
    store,
    sessionSecret: SESSION_SECRET,
    // The real ownership check, against the real table: a conversation belongs
    // to the student whose row names them. Not a stub that always agrees —
    // that would make the cross-student test below vacuous.
    authorise: async (subject, conversationId) => {
      const owned = await pool.query(
        "SELECT 1 FROM conversations WHERE id = $1 AND student_id = $2",
        [conversationId, subject],
      );
      return owned.rowCount === 1;
    },
    now: () => NOW,
    publicDir: clientDir,
    // The internal append route, so a test can write a lifecycle transition the
    // way the Secure Interaction Service does — over HTTP, with a credential —
    // rather than by reaching into the database behind the service's back.
    authoriseService: (req) => req.header("x-service-cert") === SERVICE_CERT,
    // Fast, so a test that waits for a poll does not wait for a second.
    pollIntervalMs: 150,
    heartbeatIntervalMs: 2_000,
    // Short, so the reconnect the drop test needs happens in a test's lifetime.
    // In production this is five minutes and exists so a rolling deployment can
    // drain an instance; here it is the mechanism that severs a live stream.
    maxStreamMs: 1_500,
    issueSessionFor: (req) => {
      const subject = (req.body as { subject?: unknown } | undefined)?.subject;
      return typeof subject === "string" ? subject : null;
    },
  });
  server = await new Promise<Server>((resolve) => {
    const listening = app.listen(PORT, "127.0.0.1", () => resolve(listening));
  });
  // An extra `request` listener alongside the app's own. It only reads, so it
  // cannot change what the service does, and it sees every request the service
  // sees — including the reconnects the browser makes by itself, which are the
  // ones no client-side assertion can observe reliably.
  server.on("request", (req, res) => {
    if (!(req.url ?? "").includes("/stream")) return;
    // Node types a header as `string | string[]`, because a client may send it
    // twice. The service reads it with `req.header()`, which takes the first,
    // so this observer takes the first too — an observer that disagreed with
    // the code it observes would report on a value nothing acted on.
    const raw = req.headers["last-event-id"];
    const observation: StreamObservation = {
      resumeFrom: (Array.isArray(raw) ? raw[0] : raw) ?? null,
      delivered: [],
    };
    streamObservations.push(observation);
    // Reading the frames the service writes, because "duplicates nothing"
    // asserted on the page is asserted AFTER the client deduplicates by
    // ordinal — which is exactly the "the paged load alone would produce the
    // same list" trap, one level down. A service that ignored the cursor and
    // replayed the conversation on every reconnect would leave the transcript
    // correct and this array full of repeats.
    const write = res.write.bind(res) as (...args: unknown[]) => boolean;
    res.write = ((...args: unknown[]): boolean => {
      const chunk = args[0];
      if (typeof chunk === "string") {
        for (const line of chunk.split("\n")) {
          const id = /^id: (\d+)$/.exec(line);
          if (id !== null) observation.delivered.push(Number(id[1]));
        }
      }
      return write(...args);
    }) as typeof res.write;
  });
  browser = await chromium.launch({ headless: true });
}, 180_000);

afterAll(async () => {
  if (!HAVE_DATABASE) return;
  await browser.close();
  await new Promise<void>((resolve) => server.close(() => resolve()));
  await pool.end();
  await rm(clientDir, { recursive: true, force: true });
});

// ───────────────────────────────────────────────────────────────────────────
// Phase 1 — the browser reaches the real service
// ───────────────────────────────────────────────────────────────────────────

describeIfDatabase("the React client on the real Conversation Service", () => {
  it("loads an existing conversation, with the SERVER's ordinals", async () => {
    // Written before the page exists, straight into the log. What the browser
    // renders is therefore the service's transcript, not one it was handed.
    const conversation = await newConversation();
    await store.append({
      conversationId: conversation,
      event: { kind: "message", actor: "student", content: "what documents do I need?" },
    });
    await store.append({
      conversationId: conversation,
      event: { kind: "message", actor: "assistant", content: "your passport, to start" },
    });

    const page = await chatPage(conversation);
    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 10_000 })
      .toBe(2);

    const durable = await durableOf(page);
    expect(durable.map((event) => event.ordinal)).toEqual([1, 2]);
    expect(durable.map((event) => event.content)).toEqual([
      "what documents do I need?",
      "your passport, to start",
    ]);
    // And it is on screen, in order.
    expect(
      await page.locator('[data-testid="turn"]').allTextContents(),
    ).toEqual(["what documents do I need?", "your passport, to start"]);
    await page.close();
  }, 60_000);

  it("sends through the service and adopts the ordinal it is given", async () => {
    const conversation = await newConversation();
    // Two events already in the log, so a client computing `length + 1` would
    // say 1 where the server says 3. The numbers must not agree by accident.
    await store.append({
      conversationId: conversation,
      event: { kind: "message", actor: "assistant", content: "hello" },
    });
    await store.append({
      conversationId: conversation,
      event: { kind: "message", actor: "assistant", content: "still here" },
    });

    const page = await chatPage(conversation);
    await sendFromComposer(page, "and about the deposit?");

    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 10_000 })
      .toBe(3);
    const durable = await durableOf(page);
    expect(durable.map((event) => event.ordinal)).toEqual([1, 2, 3]);
    expect(durable[2]?.content).toBe("and about the deposit?");

    // The database agrees, which is the half a client cannot fake.
    const stored = await store.since(conversation, 0);
    expect(stored.map((event) => event.ordinal)).toEqual([1, 2, 3]);
    await page.close();
  }, 60_000);

  it("leaves NO provisional entry once the durable event arrives", async () => {
    const conversation = await newConversation();
    const page = await chatPage(conversation);
    await sendFromComposer(page, "does the echo survive?");

    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 10_000 })
      .toBe(1);
    // One thing on screen, not two: the echo was retired by the event that
    // superseded it. Polled rather than asserted once, because a duplicate
    // could appear a moment later when the stream delivers the same event.
    await expect
      .poll(async () => await page.locator('[data-testid="turn"]').count(), { timeout: 5_000 })
      .toBe(1);
    expect(await allOf(page)).toHaveLength(1);
    await page.close();
  }, 60_000);

  it("does not duplicate an event that arrives by BOTH response and stream", async () => {
    // The send response carries the written event, and the stream delivers the
    // same event moments later. Both paths admit it; `admitDurable` ignores an
    // ordinal it already holds, so the transcript holds one copy.
    const conversation = await newConversation();
    const page = await chatPage(conversation);

    await sendFromComposer(page, "exactly once please");
    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 10_000 })
      .toBe(1);

    // Wait past a poll interval and a stream delivery, then look again. A
    // duplicate that appears late is still a duplicate, and asserting
    // immediately would miss it.
    await page.waitForTimeout(1_200);
    const durable = await durableOf(page);
    expect(durable, JSON.stringify(durable)).toHaveLength(1);
    expect(durable[0]?.ordinal).toBe(1);
    await page.close();
  }, 60_000);

  it("refuses another student's conversation, and renders nothing of it", async () => {
    const theirs = await newConversation(otherStudentId);
    await store.append({
      conversationId: theirs,
      event: { kind: "message", actor: "student", content: "PRIVATE-TO-THE-OTHER-STUDENT" },
    });

    const page = await chatPage(theirs, studentId);
    await page.waitForTimeout(1_000);
    expect(await durableOf(page)).toEqual([]);
    expect(await page.content()).not.toContain("PRIVATE-TO-THE-OTHER-STUDENT");
    await page.close();
  }, 60_000);

  it("streams without a bearer token anywhere — the cookie is the credential", async () => {
    const conversation = await newConversation();
    const urls: string[] = [];
    const page = await chatPage(conversation);
    page.on("request", (request) => urls.push(request.url()));

    await sendFromComposer(page, "watch the wire");
    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 10_000 })
      .toBe(1);

    // No credential in any URL. ADR-0033's reason for the cookie is that
    // EventSource takes no headers, and the alternative — a token in the query
    // string — reaches the access log, the Referer and the browser history.
    for (const url of urls) {
      expect(url, url).not.toMatch(/token|session|bearer|authorization/i);
    }
    // And the cookie really is HttpOnly: script cannot read it.
    expect(await page.evaluate(() => document.cookie)).not.toContain("aas-session");
    await page.close();
  }, 60_000);
});

// ───────────────────────────────────────────────────────────────────────────
// The fail-closed guard, as a real browser experiences it
// ───────────────────────────────────────────────────────────────────────────

describeIfDatabase("a secure step blocks the composer, from the LOG", () => {
  it("blocks a page that was already open when the step was written", async () => {
    const conversation = await newConversation();
    const page = await chatPage(conversation);

    // Written the way the Secure Interaction Service writes it: through the
    // internal append route, over HTTP, with a service credential. Not injected
    // into the page — the browser is an observer of this, never its author.
    const appended = await fetch(
      `${BASE}/internal/v1/conversations/${conversation}/events`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-service-cert": SERVICE_CERT },
        body: JSON.stringify({
          kind: "secret_requested",
          requestId: `sr_${"c".repeat(32)}`,
          channel: "secure_control",
          expiresAt: new Date(NOW.getTime() + 300_000).toISOString(),
        }),
      },
    );
    expect(appended.status).toBe(201);

    // It reaches the page over the stream, and the composer closes — on the
    // strength of an event the page did not write and could not have invented.
    await expect
      .poll(async () => await page.locator("#chat-send").isDisabled(), { timeout: 15_000 })
      .toBe(true);
    // Typing is never blocked. A student who is mid-sentence keeps their words;
    // only sending is inert.
    expect(await page.locator("#chat-input").isDisabled()).toBe(false);
    await page.close();
  }, 60_000);

  it("REFUSES a stale client's message even though the client thinks it may send", async () => {
    // ═════════════════════════════════════════════════════════════════════
    // Vahid, 2026-08-28: *"A failed lifecycle push must fail closed: the
    // Conversation Service must not release the composer merely because the
    // browser believes the secure step settled."*
    // ═════════════════════════════════════════════════════════════════════
    //
    // The page here is the worst case: it holds no knowledge of the open step
    // at all, because the step was written BEFORE it loaded and its stream was
    // then severed from the transcript by loading a different conversation's
    // view of the world. What stops the message is the server reading its own
    // log — not anything the browser believes.
    const conversation = await newConversation();
    const requestId = `sr_${"d".repeat(32)}`;
    await fetch(`${BASE}/internal/v1/conversations/${conversation}/events`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-service-cert": SERVICE_CERT },
      body: JSON.stringify({
        kind: "secret_requested",
        requestId,
        channel: "secure_control",
        expiresAt: new Date(NOW.getTime() + 300_000).toISOString(),
      }),
    });

    const page = await chatPage(conversation);
    // A direct POST from the page's own context, bypassing the composer's
    // guard entirely — which is what a stale client, a broken script or a
    // hostile one would do.
    const refused = await page.evaluate(async (id) => {
      const response = await fetch(`/v1/conversations/${id}/messages`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Idempotency-Key": "a-stale-client-idempotency-key",
        },
        body: JSON.stringify({ content: "PASSWORD-TYPED-INTO-THE-WRONG-BOX" }),
      });
      return { status: response.status, body: await response.text() };
    }, conversation);

    expect(refused.status).toBe(409);
    // Nothing from the body is echoed. An echo is how a refused password
    // reaches a client-side log.
    expect(refused.body).not.toContain("PASSWORD-TYPED-INTO-THE-WRONG-BOX");
    expect(refused.body).toContain("secret_request_open");

    // And nothing was written, in the database itself.
    const bodies = await pool.query<{ n: string }>(
      "SELECT count(*) AS n FROM message_bodies WHERE content LIKE $1",
      ["%PASSWORD-TYPED-INTO-THE-WRONG-BOX%"],
    );
    expect(Number(bodies.rows[0]!.n)).toBe(0);
    await page.close();
  }, 60_000);

  it("releases only when the LOG says the step settled", async () => {
    const conversation = await newConversation();
    const requestId = `sr_${"e".repeat(32)}`;
    const internal = async (body: Record<string, unknown>): Promise<number> =>
      (
        await fetch(`${BASE}/internal/v1/conversations/${conversation}/events`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "x-service-cert": SERVICE_CERT },
          body: JSON.stringify(body),
        })
      ).status;

    await internal({
      kind: "secret_requested",
      requestId,
      channel: "secure_control",
      expiresAt: new Date(NOW.getTime() + 300_000).toISOString(),
    });
    const page = await chatPage(conversation);
    await expect
      .poll(async () => await page.locator("#chat-send").isDisabled(), { timeout: 15_000 })
      .toBe(true);

    // A REJECTION settles nothing — the student may retry, and the guard holds.
    await internal({ kind: "secret_rejected", requestId, reason: "confirmation_mismatch" });
    await page.waitForTimeout(800);
    expect(
      await page.locator("#chat-send").isDisabled(),
      "a rejection released the composer",
    ).toBe(true);

    // A cancellation does settle it, and the page learns from the stream.
    await internal({ kind: "secret_cancelled", requestId });
    await expect
      .poll(async () => await page.locator("#chat-send").isDisabled(), { timeout: 15_000 })
      .toBe(false);

    await sendFromComposer(page, "free again");
    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 10_000 })
      .toBe(4);
    await page.close();
  }, 90_000);
});

// ───────────────────────────────────────────────────────────────────────────
// Phase 2 — two real browsers on one conversation
// ───────────────────────────────────────────────────────────────────────────

describeIfDatabase("two clients on one conversation", () => {
  it("delivers one client's message to the other, and both agree on the order", async () => {
    const conversation = await newConversation();
    const first = await chatPage(conversation);
    const second = await chatPage(conversation);

    await sendFromComposer(first, "from the first tab");
    await sendFromComposer(second, "from the second tab");

    const settled = async (page: Page): Promise<number[]> =>
      (await durableOf(page)).map((event) => event.ordinal);

    await expect.poll(async () => (await settled(first)).length, { timeout: 15_000 }).toBe(2);
    await expect.poll(async () => (await settled(second)).length, { timeout: 15_000 }).toBe(2);

    // IDENTICAL ordering, not merely the same set. Two clients that agreed on
    // membership and disagreed on order would show the same conversation as two
    // different conversations.
    const fromFirst = await durableOf(first);
    const fromSecond = await durableOf(second);
    expect(fromFirst).toEqual(fromSecond);
    expect(fromFirst.map((event) => event.ordinal)).toEqual([1, 2]);

    // And the log is the authority both converged on.
    const stored = await store.since(conversation, 0);
    expect(fromFirst.map((event) => event.content)).toEqual(
      stored.map((event) => (event.kind === "message" ? event.content : null)),
    );
    await first.close();
    await second.close();
  }, 90_000);

  it("sees an event written by neither browser — the log is the source", async () => {
    const conversation = await newConversation();
    const page = await chatPage(conversation);

    // Written server-side, by nothing the page did. This is what an assistant's
    // answer, or a secure lifecycle transition, actually looks like to a client.
    await store.append({
      conversationId: conversation,
      event: { kind: "message", actor: "assistant", content: "arrived out of band" },
    });

    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 10_000 })
      .toBe(1);
    expect((await durableOf(page))[0]?.content).toBe("arrived out of band");
    await page.close();
  }, 60_000);

  it("resumes after a refresh without losing or duplicating anything", async () => {
    const conversation = await newConversation();
    const page = await chatPage(conversation);
    await sendFromComposer(page, "before the refresh");
    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 10_000 })
      .toBe(1);

    // Every stream request this page makes from here on, recorded. A refresh
    // that silently restarted the stream from 0 would still end with the right
    // transcript — the paged load would fill it in — so the transcript alone
    // cannot tell the two apart. The URL can.
    const streamUrls: string[] = [];
    page.on("request", (request) => {
      if (request.url().includes("/stream")) streamUrls.push(request.url());
    });

    // Written while the page is NOT looking, so the reload has something to
    // catch up on rather than merely re-reading what it already had.
    await page.reload();
    await page.locator('[data-testid="composer"]').waitFor({ state: "visible" });
    await store.append({
      conversationId: conversation,
      event: { kind: "message", actor: "assistant", content: "while you were away" },
    });

    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 15_000 })
      .toBe(2);
    const durable = await durableOf(page);
    expect(durable.map((event) => event.ordinal)).toEqual([1, 2]);
    expect(durable.map((event) => event.content)).toEqual([
      "before the refresh",
      "while you were away",
    ]);

    // ── The resume was by ORDINAL, not from the beginning ─────────────
    //
    // A fresh EventSource sends no `Last-Event-ID` — the browser API accepts no
    // request headers, and there is no previous connection for it to report on.
    // So the page must say where it got to in the query string, or the service
    // would re-send the whole conversation on every refresh and announce
    // `resumingAfter: 0`, which is not what the client needs resuming after.
    expect(streamUrls, "the page opened no stream after reloading").not.toHaveLength(0);
    expect(streamUrls.at(-1)).toContain("lastEventId=1");
    await page.close();
  }, 90_000);

  it("reconstructs the SAME transcript on a fresh page as the one that wrote it", async () => {
    const conversation = await newConversation();
    const author = await chatPage(conversation);
    await sendFromComposer(author, "one");
    await expect
      .poll(async () => (await durableOf(author)).length, { timeout: 10_000 })
      .toBe(1);
    await sendFromComposer(author, "two");
    await expect
      .poll(async () => (await durableOf(author)).length, { timeout: 10_000 })
      .toBe(2);

    const observer = await chatPage(conversation);
    await expect
      .poll(async () => (await durableOf(observer)).length, { timeout: 10_000 })
      .toBe(2);
    expect(await durableOf(observer)).toEqual(await durableOf(author));
    await author.close();
    await observer.close();
  }, 90_000);

  it("survives the stream dropping: reconnects, misses nothing, duplicates nothing", async () => {
    const conversation = await newConversation();
    const page = await chatPage(conversation);

    // ── The precondition the old version of this test left to luck ──────
    //
    // `EventSource` sends `Last-Event-ID` only once it has actually received
    // an `id:` line — the header is its account of what it received, and a
    // connection that received nothing has nothing to account for. So the
    // stream must deliver an event BEFORE the drop, or the reconnect that
    // follows legitimately carries no header and this test would be asserting
    // something the design never promised.
    //
    // Appending to the store, rather than sending from the composer, is what
    // makes that deterministic: a composer send also returns the event in its
    // own POST response (ADR-0031), so the page can reach one durable event
    // without the stream having carried anything. An event written straight to
    // the log has no such second path — the stream is the only way the page
    // can learn it, so holding it proves the stream delivered it.
    await store.append({
      conversationId: conversation,
      event: { kind: "message", actor: "assistant", content: "before the drop" },
    });
    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 15_000 })
      .toBe(1);

    // ── The drop ──────────────────────────────────────────────────────
    //
    // The SERVER closes the connection, on the `maxStreamMs` schedule above.
    // Two earlier attempts did not actually drop anything, and both would have
    // passed while proving nothing:
    //
    //   `page.route(...).abort()` — routing only affects requests a page has
    //   yet to make, and the EventSource connection is already open, so the
    //   pattern matched nothing.
    //
    //   `context.setOffline(true)` — Chromium's offline emulation did not sever
    //   the established loopback connection; events kept arriving, which the
    //   "nothing can arrive while offline" assertion caught.
    //
    // Closing it server-side is also the realistic case: it is what a load
    // balancer's connection-age cap does, and what a rolling deployment needs
    // in order to drain an instance. The reconnect that follows is the
    // browser's own — `EventSource` retries by itself and re-sends
    // `Last-Event-ID` carrying the last `id:` it saw, which is the mechanism
    // ADR-0035 chose SSE for and which no stubbed transport can exercise.
    const before = streamObservations.length;
    const sinceDrop = (): (string | null)[] => resumeCursors().slice(before);

    // Two events, written while the connection is being closed and remade.
    await store.append({
      conversationId: conversation,
      event: { kind: "message", actor: "assistant", content: "during the drop" },
    });
    await store.append({
      conversationId: conversation,
      event: { kind: "message", actor: "assistant", content: "still during" },
    });

    await expect
      .poll(async () => (await durableOf(page)).length, { timeout: 30_000 })
      .toBe(3);
    const durable = await durableOf(page);
    expect(durable.map((event) => event.ordinal), "a gap or a repeat").toEqual([1, 2, 3]);
    expect(durable.map((event) => event.content)).toEqual([
      "before the drop",
      "during the drop",
      "still during",
    ]);

    // ── Did the browser actually reconnect, and resume by ordinal? ────
    //
    // The transcript being right is not proof: the paged load alone would
    // produce the same list. Two things are: a NEW stream request after the
    // first was closed, and that request carrying `Last-Event-ID` — the
    // browser's own account of where it got to, which is the header the whole
    // resumability design turns on.
    //
    // Read from the SERVICE's record, so what is asserted is what arrived and
    // was acted on, not what a client-side listener managed to observe.
    await expect
      .poll(() => sinceDrop().length, { timeout: 20_000 })
      .toBeGreaterThan(0);

    // Not "at least one carried it" — EVERY one did. Once the connection has
    // received an event, a reconnect that drops the cursor would silently
    // replay the conversation from the beginning, and a test that tolerated
    // one such request would not notice.
    expect(
      sinceDrop(),
      "a reconnect carried no Last-Event-ID, so it resumed from the beginning",
    ).not.toHaveLength(0);
    for (const value of sinceDrop()) {
      expect(value, "a reconnect lost the cursor").not.toBeNull();
      expect(/^[0-9]+$/.test(value ?? ""), `not an ordinal: ${String(value)}`).toBe(true);
    }

    // And the cursor TRACKS the log rather than merely existing: once all three
    // events have been delivered, the next reconnect asks to resume after the
    // third. This is the assertion that would fail if the header were stale or
    // if the service ignored it and replayed from zero.
    await expect
      .poll(() => Math.max(...sinceDrop().map((value) => Number(value ?? 0))), { timeout: 20_000 })
      .toBe(3);

    // And the SERVICE honoured it. Every reconnect after the drop asked to
    // resume after some ordinal; none of them may re-send an ordinal at or
    // below what was asked for. Without this, a service that ignored the
    // header and replayed from zero would still pass everything above, because
    // the client deduplicates what it already holds.
    for (const observation of streamObservations.slice(before)) {
      const cursor = Number(observation.resumeFrom ?? 0);
      expect(
        observation.delivered.filter((ordinal) => ordinal <= cursor),
        `the service re-sent events at or below the cursor ${String(cursor)}`,
      ).toEqual([]);
    }
    // Across every connection, no ordinal was ever put on the wire twice.
    const wire = streamObservations.slice(before).flatMap((o) => o.delivered);
    expect(wire, "an event was delivered twice on the wire").toEqual([...new Set(wire)]);
    await page.close();
  }, 120_000);

  it("a stream recycled before any event exists still delivers what arrived while it was down", async () => {
    // The ordering that used to break the test above, now a property in its
    // own right. A page opens on an EMPTY conversation, so the first stream
    // connection carries no cursor in its URL and receives no `id:` before the
    // service recycles it on the `maxStreamMs` schedule. The browser therefore
    // reconnects with NO `Last-Event-ID` — correctly, because it has received
    // nothing — and the service resumes that stream from the beginning.
    //
    // Nothing about that is a fault, and the point of this test is that it must
    // stay harmless: everything appended while the connection was down still
    // arrives, exactly once, in order. Before this test existed the behaviour
    // was real but unasserted, and the only thing that noticed it was a sibling
    // test failing on a slower machine for a reason that looked like a flake.
    const conversation = await newConversation();
    const page = await chatPage(conversation);
    const before = streamObservations.length;

    // Long enough for the first connection to be recycled and the browser to be
    // between attempts. `maxStreamMs` is 1.5s and Chromium's reconnect delay is
    // ~3s, so this lands inside the gap rather than merely after the close.
    await expect
      .poll(() => streamObservations.length, { timeout: 20_000 })
      .toBeGreaterThan(before);

    // The reconnect a connection that received nothing makes: no cursor, and
    // none to be had. If this ever carries one, the premise of the test above
    // has changed and it should be revisited rather than quietly passing.
    expect(
      resumeCursors().slice(before),
      "a stream that received no event still claimed a cursor",
    ).toEqual(resumeCursors().slice(before).map(() => null));

    for (const content of ["first while down", "second while down", "third while down"]) {
      await store.append({
        conversationId: conversation,
        event: { kind: "message", actor: "assistant", content },
      });
    }

    // Polling on the ORDINALS, not on a count. A count that never arrives
    // fails as a bare "matcher did not succeed", which says nothing about what
    // went wrong; polling the list means the failure prints what the page
    // actually holds — `[]` for events that never came, `[1, 3]` for a gap.
    await expect
      .poll(async () => (await durableOf(page)).map((event) => event.ordinal), { timeout: 30_000 })
      .toEqual([1, 2, 3]);
    const durable = await durableOf(page);
    expect(durable.map((event) => event.content)).toEqual([
      "first while down",
      "second while down",
      "third while down",
    ]);
    await page.close();
  }, 120_000);
});
