/**
 * The per-area test census, generated from a real run.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * `docs/state-of-the-system.md` §7 carried this table by hand, and P50 measured
 * it: SIX of twenty rows were wrong, and the table did not add up.
 *
 *     its rows summed to               1,824
 *     plus its own "everything else"    ~346
 *                                     ------
 *                                      2,170
 *     against its own stated total      2,306
 *
 * A hundred and thirty-six tests unaccounted for, every drift in the SAME
 * direction — the table understated the suite, exactly as P49's stale index
 * understated the decisions. Nobody had lied; the numbers had simply been true
 * once.
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * ── Why this one IS generated, when ADR-0082 refused ──────────────────────
 *
 * P48 was asked the same question about the declared-but-unreachable table and
 * answered no, because that table's second column is *"why it is kept"* — a
 * judgement citing ADR-0019 and ADR-0071, which a generator would either drop
 * or force into a checker that is not a place to argue.
 *
 * This table has no such column. It is twenty area names and twenty integers,
 * and there is nothing in it a person knows that a run does not. A number a
 * person must recount by hand to verify is one that will be wrong, and this one
 * was wrong for weeks in a document the README says to read first.
 *
 * Same question, opposite answer, and the content is the reason.
 *
 * ── Usage ─────────────────────────────────────────────────────────────────
 *
 *     pnpm run census        # runs the suite and rewrites the table
 *
 * It rewrites only between the two markers in §7, so the prose around it — the
 * lane explanation, the coverage argument — is untouched.
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const ROOT = resolve(join(import.meta.dirname, ".."));
const DOCUMENT = join(ROOT, "docs", "state-of-the-system.md");

export const CENSUS_BEGIN = "<!-- census:begin — generated by `pnpm run census`, do not edit by hand -->";
export const CENSUS_END = "<!-- census:end -->";

/**
 * Areas small enough that a row of their own would be noise.
 *
 * They are summed into "everything else", which is an EXACT figure and not an
 * approximation — the old table's "~346" is what let the arithmetic drift 136
 * without anybody noticing, because a tilde absorbs any error.
 */
const ROW_THRESHOLD = 20;

interface AreaCount {
  readonly area: string;
  readonly tests: number;
}

/** The workspace directory a test file belongs to, or `scripts`. */
function areaOf(file: string): string {
  const relative = file.startsWith(ROOT) ? file.slice(ROOT.length + 1) : file;
  const match = /^(packages\/[^/]+|apps\/[^/]+|scripts)\//.exec(relative);
  return match?.[1] ?? "scripts";
}

export function countsFrom(report: string): {
  readonly areas: readonly AreaCount[];
  readonly total: number;
} {
  const parsed: unknown = JSON.parse(report);
  const results = (parsed as { testResults?: { name: string; assertionResults: unknown[] }[] })
    .testResults;
  if (results === undefined) throw new Error("the report has no testResults");

  const tally = new Map<string, number>();
  let total = 0;
  for (const file of results) {
    const area = areaOf(file.name);
    const n = file.assertionResults.length;
    tally.set(area, (tally.get(area) ?? 0) + n);
    total += n;
  }

  const areas = [...tally.entries()]
    .map(([area, tests]) => ({ area, tests }))
    .sort((a, b) => b.tests - a.tests || a.area.localeCompare(b.area));

  return { areas, total };
}

export function tableFrom(areas: readonly AreaCount[], total: number): string {
  const listed = areas.filter((a) => a.tests >= ROW_THRESHOLD);
  const rest = total - listed.reduce((sum, a) => sum + a.tests, 0);

  const cells = [
    ...listed.map((a) => `\`${a.area}\` | ${String(a.tests)}`),
    `everything else | ${String(rest)}`,
  ];

  // Two columns, filled down the left then the right, so the biggest areas read
  // first in each.
  const half = Math.ceil(cells.length / 2);
  const rows: string[] = [];
  for (let i = 0; i < half; i++) {
    rows.push(`| ${cells[i] ?? " | "} | ${cells[i + half] ?? " | "} |`);
  }

  return [
    CENSUS_BEGIN,
    "",
    `**${total.toLocaleString("en-GB")} tests**, by the workspace they live in. Generated — run`,
    "`pnpm run census` after changing the suite. The rows and *everything else* sum to the total",
    "exactly; the figure this replaced was approximate and had drifted 136 tests without anyone",
    "being able to see it (ADR-0084).",
    "",
    "| Area | Tests | Area | Tests |",
    "|---|---|---|---|",
    ...rows,
    "",
    CENSUS_END,
  ].join("\n");
}

/**
 * Runs the suite and returns its report, along with whether it passed.
 *
 * ── A red suite must still be countable ───────────────────────────────────
 *
 * The first version threw on a non-zero exit, and deadlocked immediately:
 * `census.test.ts` fails while the table is stale, so the suite is red, so the
 * census cannot run, so the table stays stale. That is not an edge case — it is
 * the NORMAL case, because the reason to run a census is that the suite has
 * changed and the table has not.
 *
 * So the report is read whichever way the run went, the table is written, and
 * the exit code is passed through afterwards. `pnpm run census` regenerates the
 * table AND tells the truth about the run; it never quietly reports a green
 * suite it did not get.
 */
function runSuite(): { readonly report: string; readonly passed: boolean } {
  const directory = mkdtempSync(join(tmpdir(), "census-"));
  const out = join(directory, "results.json");
  try {
    let passed = true;
    try {
      // `default` as well as `json`, so a red run still prints the failing test
      // NAMES. The first version passed only `json`, which would have made a
      // failing CI job print a machine report and nothing a person can read.
      execFileSync(
        "npx",
        ["vitest", "run", "--reporter=default", "--reporter=json", `--outputFile=${out}`],
        {
          cwd: ROOT,
          stdio: "inherit",
        },
      );
    } catch {
      passed = false;
    }
    if (!existsSync(out)) {
      throw new Error("the suite produced no report at all — nothing to count");
    }
    return { report: readFileSync(out, "utf8"), passed };
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

/** The test files with at least one failure, for the message on a red run. */
function failingFiles(report: string): readonly string[] {
  const parsed: unknown = JSON.parse(report);
  const results =
    (parsed as { testResults?: { name: string; status?: string }[] }).testResults ?? [];
  return results
    .filter((file) => file.status === "failed")
    .map((file) => (file.name.startsWith(ROOT) ? file.name.slice(ROOT.length + 1) : file.name));
}

function main(): void {
  console.log("Running the suite to count it…\n");
  const { report, passed } = runSuite();
  const { areas, total } = countsFrom(report);

  const document = readFileSync(DOCUMENT, "utf8");
  const start = document.indexOf(CENSUS_BEGIN);
  const end = document.indexOf(CENSUS_END);
  if (start === -1 || end === -1) {
    console.error(`No census markers in ${DOCUMENT}. Expected:\n  ${CENSUS_BEGIN}\n  ${CENSUS_END}`);
    process.exitCode = 1;
    return;
  }

  const rewritten =
    document.slice(0, start) + tableFrom(areas, total) + document.slice(end + CENSUS_END.length);
  writeFileSync(DOCUMENT, rewritten, "utf8");

  console.log(`\nCensus written: ${String(total)} tests across ${String(areas.length)} areas.`);

  if (!passed) {
    const failed = failingFiles(report);
    console.error(
      `\nTHE SUITE IS RED — the census above counts a run that failed in ` +
        `${String(failed.length)} file(s):\n` +
        failed.map((file) => `  ✗  ${file}`).join("\n") +
        `\n\nThe table is written because a stale table is itself a reason the suite is red. ` +
        `The exit code is not swallowed.`,
    );
    process.exitCode = 1;
  }
}

// Run only when this file IS the program — `census.test.ts` imports the pure
// functions above, and an import that ran the whole suite would be absurd.
// (ADR-0082 §4, for the same reason and with the same shape.)
const invokedDirectly = process.argv[1]?.endsWith("census.ts") ?? false;
if (invokedDirectly) main();
